### ISSUE TITLE
support excluding namespace from being matched by wildcards

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/secretgen-controller#38]
**Describe the problem/challenge you have**

currently users of SecretExport may specify `toNamespace: "*"`. there might be namespaces in the cluster that cluster administrators would want to section off from receiving any secrets unless SecretExport explicitly specifies namespace selection.

**Describe the solution you'd like**
one idea in how to mark such namespaces is via annotation (on a namespace) -- `secretgen.carvel.dev/excluded-from-wildcard-matching: ""`

**Comment by danielhelfand** [comment]
Making some notes here:
* We need to update the [RBAC](https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/10089556361f662133c8e8bf0be9596f8791ef0a/config/rbac.yml#L14) to allow getting namespaces
* We should also add some [docs](https://github.com/vmware-tanzu/carvel-secretgen-controller/tree/develop/docs) that mention this annotation / how to use it

**Comment by aaronshurley** [comment]
This has been delivered as a part of [v0.7.0](https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/tag/v0.7.0). But, we recommended using [v0.7.1](https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/tag/v0.7.1).

**Comment by jorgemoralespou** [comment]
Seems as this feature got implemented and merged already. I'm not still convinced by this solution, as it means that the author of a package (let's say my training-package) would need to add this annotation to my namespace definition just to prevent from secretgen controller to inject me a secret even if I, as package author don't know whether my package is going to be deployed in a cluster where secretgen controller does exist. This means that this solution introduces a dependency on package authors to add an annotation just in case.
I would think that operators/cluster admins that are installing features on the cluster and that create a secretgen are the ones that know which capabilities exist and whether they should prevent secretgen from leaking secrets into namespaces that it shouldn't. For this reason, I think that this solution solves the problem for one specific use-case, but definitely there will be reports to implement this feature in a more sustainable manner (for package authors) in the future.

The responsibility issue can probably be solved by documenting how to create an overlay in the package to have this annotation added so that a COTS package can exclude the wildcard secretgen.
