### ISSUE TITLE
 instruct secret gen controller to leave out certain annotations and labels while copying the secrets

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/secretgen-controller#47]
**Describe the problem/challenge you have**
Shreyas Sreenivas  21 hours ago
Hi,
Needed some inputs regarding the Secret-Gen-Controller SecretImport implementation and possible changes.
Secret Import duplicates the secret into a new namespace. This duplicated secret duplicates all the Annotations and Labels from the source secret (DeepCopy of the secret). This is causing an issue in the TMC managedSecret controller, this duplicate secret is getting cleaned up as the controller use annotations to map it against the server intent and the duplicate secret has the same unique identifier (TMC related ID ) in the secret annotations.

Your thoughts and suggestion on solving this problem ? (edited) 

**Describe the solution you'd like**
Request for change:
Can secret gen controller on duplication of the secret add an extra annotation which depicts that the secret is created via secret-import. In the present implementation, we see that the duplicate secret does have a owner ref to secret import CR, but annotation should be simpler. By this change we can avoid the secret getting deleted from the controller

OR, can the secret gen controller avoid copying the annotations of the secrets ?

**Anything else you would like to add:**
In slack thread it looked like there were two votes for the second proposal ("avoid copying certain annotations")

**Comment by joe-kimmel-vmw** [comment]
Implementation options:

1. sgc always adds its own annotation to copied secrets (like a watermark)
2. sgc.secretImport and gets an "exclusion list" for annotations and it filters the annotations on the new secret against that exclusion list
3. sgc.secretImport and gets a "annotations list" of annotations that the user wants added to the new secret (like a custom watermark - a monogram!)
4. sgc secret copying avoids copying annotations entirely (based on skimming the current test suite, it doesn't look like we thought it was important to copy annotations previously?)

We'll allow a little period for comments / opinions re. the three above options to surface-  maybe 1 week?

Expectations that do still hold:
- if a source secret is deleted, the source-secret's data should be deleted from the copy

**Comment by joe-kimmel-vmw** [comment]
want to note per this test,  and contrary to the earlier writeup,  that actually placeholder secrets don't have annotations copied,  so it's actually only for secret imports.
I edited one of our existing tests to prove this:
https://github.com/vmware-tanzu/carvel-secretgen-controller/pull/48

**Comment by GrahamDumpleton** [comment]
My experience has been that copying across existing annotations/labels from a secret was always a bad idea. It would muck up things like kapp or other tools that used annotations/labels to track ownership for a deployment etc. In secret copiers I have written have thus never done that, although did allow in the custom resource rule for setting up copying of a secret to allow users to explicitly provide their own set of labels (not annotations) that should be set on the copy of the original secret. I would always add annotations to the copy indicating that what was copied by the secret copier operator, including a reference to namespace/name of resource for the copying rule, so you could track the origin and know where the copy of the secret came from.

It is unfortunate that annotations/labels were being copied because now it is going to be hard to unwind that and make the default not copy them, even though that is the better default strategy.
